language: go
go:
- 1.8
- 1.9
- master
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go build -v
  - go test -v -cover ./...
